=== DmitriyMX/Trader/core/src/main/resources/store/trader.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="market" type="marketType"/>

    <xs:complexType name="marketType">
        <xs:sequence>
            <xs:element name="items" type="itemsType"/>
            <xs:element name="places" type="placesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="placesType">
        <xs:sequence>
            <xs:element name="place" type="placeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="servicesType">
        <xs:sequence>
            <xs:element name="service" type="serviceType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="itemsType">
        <xs:sequence>
            <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="item" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="groupType">
        <xs:sequence>
            <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="GROUP_TYPE" use="required"/>
    </xs:complexType>

    <xs:simpleType name="GROUP_TYPE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MARKET"/>
            <xs:enumeration value="SHIP"/>
            <xs:enumeration value="OUTFIT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="itemType">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="placeType" mixed="true">
        <xs:sequence>
            <xs:element name="vendor" type="vendorType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="x" type="xs:double" use="optional"/>
        <xs:attribute name="y" type="xs:double" use="optional"/>
        <xs:attribute name="z" type="xs:double" use="optional"/>
    </xs:complexType>

    <xs:complexType name="vendorType" mixed="true">
        <xs:sequence>
            <xs:element name="services" type="servicesType"/>
            <xs:element name="offer" type="offerType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="distance" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="serviceType">
        <xs:attribute name="type" type="SERVICE_TYPE" use="required"/>
    </xs:complexType>

    <xs:simpleType name="SERVICE_TYPE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MARKET"/>
            <xs:enumeration value="BLACK_MARKET"/>
            <xs:enumeration value="REPAIR"/>
            <xs:enumeration value="MUNITION"/>
            <xs:enumeration value="OUTFIT"/>
            <xs:enumeration value="SHIPYARD"/>
            <xs:enumeration value="MEDIUM_LANDPAD"/>
            <xs:enumeration value="LARGE_LANDPAD"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="offerType">
        <xs:attribute name="item" type="xs:IDREFS" use="required"/>
        <xs:attribute name="type" type="OFFER_TYPE" use="required"/>
        <xs:attribute name="price" type="xs:double" use="required"/>
        <xs:attribute name="count" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:simpleType name="OFFER_TYPE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SELL"/>
            <xs:enumeration value="BUY"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== DmitriyMX/Trader/core/src/test/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<market xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "../../main/resources/store/trader.xsd">
    <items>
        <item name="Item 1" id="i1"/>
        <item name="Item 2" id="i2"/>
        <item name="Item 3" id="i3"/>
        <item name="Item 4" id="i4"/>
        <item name="Item 5" id="i5"/>
        <item name="Item 6" id="i6"/>
    </items>
    <places>
        <vendor name="Vendor 1">
            <offer item="i1" type="SELL" price="140"/>
        </vendor>

        <vendor name="Empty system" x="1" y="2" z="3"/>

    </places>
</market>
